export declare const test_0: any;
export declare const test_1: unknown;
export declare const test_2: string;
export declare const test_3: number;
export declare const test_4: boolean;
export declare const test_5: string | number;
export declare const test_6: string | boolean;
export declare const test_7: unknown;
export declare const test_8: unknown;
export declare const test_9: unknown;
export declare const test_10: unknown;
export declare const test_11: unknown;
export declare const test_12: unknown;
export declare const test_7b: any;
export declare const test_8b: any;
export declare const test_9b: any;
export declare const test_10b: any;
export declare const test_11b: any;
export declare const test_12b: any;
export declare const test_7c: Date;
export declare const test_8c: Date;
export declare const test_9c: Date;
export declare const test_10c: Date;
export declare const test_11c: Date;
export declare const test_12c: Date;
