export declare const test_0: never;
export declare const test_1: never;
export declare const test_2: string;
export declare const test_3: number;
export declare const test_4: boolean;
export declare const test_5: string | number;
export declare const test_6: string | boolean;
export declare const test_7: string;
export declare const test_8: string | number;
export declare const test_9: number;
export declare const test_10: boolean;
export declare const test_11: number;
export declare const test_12: string | boolean;
export declare const test_7b: string;
export declare const test_8b: string | number;
export declare const test_9b: number;
export declare const test_10b: boolean;
export declare const test_11b: number;
export declare const test_12b: string | boolean;
export declare const test_7c: Date;
export declare const test_8c: Date;
export declare const test_9c: Date;
export declare const test_10c: Date;
export declare const test_11c: Date;
export declare const test_12c: Date;
